# -*- coding: utf-8 -*-
"""2022-0607_recipie321_module.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rzK3eAZIkHOLMeDnX_-Ot2zR3wVQNvR5
"""

def kaijou(n):
  m = 1
  for i in range(n):
    m = m*(i+1)
  return m